# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@3.8
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'