# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/jmux
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - run:
          name: Build Project
          command: mvn package
      - persist_to_workspace:
          root: .
          paths:
            - target/
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/jmux
    steps:
      - attach_workspace:
          at: ~/jmux
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build